### ISSUE TITLE
Use on server

### ISSUE THREAD

**Issue by platindev** [cdown/yturl#34]
Hello,
Can I use that script on server. I am finding a solution like playit.pk player play the video.

**Comment by cdown** [comment]
Hey @platindev,

Not sure what your question is. You can use yturl on a server, but if you're going to display the URIs to users, there is one limitation -- that the URLs YouTube generates are limited to the requesting party's IP space. This is a YouTube (presumably intentional) limitation, not a yturl one.

Other than that it will work fine, servers are fundamentally no different than any other computer after all. :-)

**Comment by platindev** [comment]
Thanks for reply. I am just looking for a open source script like http://de2.ytapi.com/python/
But not find yet.

**Comment by cdown** [comment]
Well, let me know if you have any trouble. I'll close out until then. :-)

**Comment by platindev** [comment]
Yeh sure. Is there a way to talk with you. Not in the ticket. May you can guide and help me out of few things to understand.

**Comment by cdown** [comment]
Sorry, I don't have time for 1:1 help.

**Comment by platindev** [comment]
NP. I will say to you if I will have. Just configuring python at my server. Then will look over it. You can mark it as close at the moment. And thank for the time and sorry to disturb you. It's not about the project that want to discuss. But as I have started learning Python myself also. The question or help was from that side. I know the answer is big over internet. But don't find answers their too. You can write me umerkakar {at} gmail.com whenever get time and want to help out please. I have some ideas in mind.
